services:
  - type: web
    name: micro-entrepreneur-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: micro-entrepreneur-db
          property: connectionString
    autoDeploy: true

databases:
  - name: micro-entrepreneur-db
    databaseName: micro_entrepreneur
    user: micro_entrepreneur_user
    region: oregon
    plan: free
    ipAllowList: []
